<?php

/**
 * @file
 * Contains affiliates_connect.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * Main module help for the affiliates_connect module.
 */

function affiliates_connect_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {

    case 'affiliates_connect.overview':
      $template_path = drupal_get_path('module', "affiliates_connect") . "/templates/help.html.twig";
      $template = file_get_contents($template_path);
      $build = [
        'description' => [
          '#type' => 'inline_template',
          '#template' => $template,
        ],
      ];
      return $build;

    default:
  }

}
