<?php

/**
 * @file
 * Contains affiliates_connect_amazon.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function affiliates_connect_amazon_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the affiliates_connect_amazon module.
    case 'help.page.affiliates_connect_amazon':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Amazon Plugin') . '</p>';
      return $output;

    default:
  }
}
