affiliates_connect.settings:
  type: config_object
  label: 'Affiliates Connect Settings'
  mapping:
    use_fallback_scraper:
      type: boolean
      label: 'Allows Scraper API to search if Native API fails'
    save_searched_products:
      type: boolean
      label: 'Save Searched Products data in database if not found in database'
    cloaking:
      type: boolean
      label: 'Hide Affiliate ID in Affiliate URLs'
    enable_hits_analysis:
      type: boolean
      label: 'Allows to count & analysis user hits on cloaking urls'
    append_affiliateid_scraped_products_url:
      type: boolean
      label: 'Enable to automatically append affiliate tracking id to products url during scraping'
