affiliates_connect.settings:
  type: config_object
  label: 'Affiliates Connect Settings'
  mapping:
    fallback_scraper:
      type: boolean
      label: 'Allows Scraper API to search when Native API fails'
    save_searched_products:
      type: boolean
      label: 'Save searched products data in database if not found in database'
    cloaking:
      type: boolean
      label: 'Hide Affiliate IDs in Affiliate URLs'
    enable_hits_analysis:
      type: boolean
      label: 'Allows counting & analysis of user hits on cloaking urls'
    append_affiliate_id:
      type: boolean
      label: 'Enable to automatically append Affiliate tracking ID to products URL during scraping'
