affiliates_connect_amazon.settings:
  type: config_object
  label: 'Affiliates Connect Amazon settings'
  mapping:
    native_api:
      type: boolean
      label: 'Allows usage Affiliate Marketing using tracking ID'
    native_affiliate_id:
      type: string
      label: 'Input associated ID of corresponding Affiliate API'
    native_affiliate_token:
      type: string
      label: 'Input associated token of corresponding Affiliate API'
    scraper_api:
      type: boolean
      label: 'Allows usage Scraper API to overcome limitation of Affiliate API'

